// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjdnpprinmfopgcrqtbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqZG5wcHJpbm1mb3BnY3JxdGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MTYxNDEsImV4cCI6MjA2MjA5MjE0MX0.v_GC2shC1m3zb3vGoxtPviM-i3cneAICgOhAp9zb_9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);